// GENERATED by tools/build.py from content/src/syndromes.json and content/src/districts.json. Do not edit by hand.
export default {
 "version": "2026-10-07.1",
 "dedupeDays": 14,
 "ageGroups": [
  {
   "id": "u5",
   "en": "Child under 5",
   "fa": "طفل زیر ۵ سال",
   "ps": "له ۵ کلونو کم ماشوم"
  },
  {
   "id": "5-14",
   "en": "Older child (5 to 14)",
   "fa": "طفل بزرگتر (۵ تا ۱۴ سال)",
   "ps": "لوی ماشوم (۵ تر ۱۴ کلونو)"
  },
  {
   "id": "15+",
   "en": "Adult (15 and over)",
   "fa": "بزرگسال (۱۵ سال و بیشتر)",
   "ps": "لوی (۱۵ کلن او پورته)"
  }
 ],
 "syndromes": [
  {
   "id": "measles",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Any person with fever and a maculopapular (non-vesicular) rash, or in whom a health worker suspects measles. App wording: fever and a red rash all over the body.",
   "topics": [
    "measles",
    "fever"
   ],
   "symptoms": [
    "rash"
   ],
   "source": {
    "title": "WHO Vaccine-Preventable Diseases Surveillance Standards: Measles (2018)",
    "url": "https://www.who.int/teams/immunization-vaccines-and-biologicals/immunization-analysis-and-insights/surveillance/surveillance-for-vpds/vpd-surveillance-standards"
   },
   "en": "Suspected measles",
   "fa": "سرخکان (مشکوک)",
   "ps": "شری (شکمن)",
   "ask": "Fever and a red rash all over the body; it may be measles."
  },
  {
   "id": "awd",
   "active": true,
   "version": 2,
   "history": [
    {
     "version": 1,
     "until": "2026-10-07",
     "topics": [
      "diarrhoea"
     ]
    }
   ],
   "definition": "Three or more loose or watery stools in 24 hours, without visible blood.",
   "topics": [
    "diarrhoea",
    "diarrhoea-adult"
   ],
   "symptoms": [
    "diarrhoea"
   ],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Acute watery diarrhoea",
   "fa": "اسهال آبکی حاد",
   "ps": "حاد اوبلن نس ناستی",
   "ask": "Three or more watery stools in one day, with no blood."
  },
  {
   "id": "bloody-diarrhoea",
   "active": true,
   "version": 2,
   "history": [
    {
     "version": 1,
     "until": "2026-10-07",
     "topics": [
      "diarrhoea"
     ]
    }
   ],
   "definition": "Acute diarrhoea with visible blood in the stool.",
   "topics": [
    "diarrhoea",
    "diarrhoea-adult"
   ],
   "symptoms": [
    "diarrhoea"
   ],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Bloody diarrhoea",
   "fa": "اسهال خونی",
   "ps": "وینه لرونکی نس ناستی",
   "ask": "Diarrhoea, with blood in the stool."
  },
  {
   "id": "ari",
   "active": true,
   "version": 2,
   "history": [
    {
     "version": 1,
     "until": "2026-10-07",
     "topics": [
      "cough"
     ]
    }
   ],
   "definition": "Cough or difficult breathing with fast breathing (IMCI cut-offs by age) or lower chest indrawing (ARI-pneumonia). Lay report, breathing not counted by a health worker.",
   "topics": [
    "cough",
    "pneumonia-adult"
   ],
   "symptoms": [
    "breathing",
    "cough"
   ],
   "source": {
    "title": "WHO IMCI Chart Booklet (2014) and WHO EMRO Afghanistan outbreak situation reports (ARI-pneumonia)",
    "url": "https://www.emro.who.int/images/stories/afghanistan/Afghanistan-Outbreaks-Situation-report-week-43-2025.pdf"
   },
   "en": "Acute respiratory infection / pneumonia",
   "fa": "سینه‌بغل / التهاب حاد تنفسی",
   "ps": "سینه بغل / حاد تنفسي انتان",
   "ask": "Cough with fast or difficult breathing."
  },
  {
   "id": "cchf",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Sudden onset of fever with bleeding (nose, gums, skin, vomit or stool), especially after a tick bite or contact with animal blood or a sick person. Immediately notifiable.",
   "topics": [
    "animal-illness"
   ],
   "symptoms": [
    "animals"
   ],
   "source": {
    "title": "WHO fact sheet: Crimean-Congo haemorrhagic fever; WHO EMRO Afghanistan outbreak situation reports (suspected CCHF)",
    "url": "https://www.who.int/news-room/fact-sheets/detail/crimean-congo-haemorrhagic-fever"
   },
   "en": "Suspected CCHF (Congo fever)",
   "fa": "تب کانگو (مشکوک)",
   "ps": "کانګو تبه (شکمنه)",
   "ask": "Sudden fever with bleeding from the nose, gums or under the skin."
  },
  {
   "id": "dog-bite",
   "active": true,
   "version": 2,
   "history": [
    {
     "version": 1,
     "until": "2026-10-07",
     "topics": [
      "first-aid",
      "animal-illness"
     ]
    }
   ],
   "definition": "Any person bitten or scratched by a dog or another animal that may carry rabies (possible rabies exposure).",
   "topics": [
    "first-aid",
    "animal-illness",
    "dog-bite"
   ],
   "symptoms": [
    "bite"
   ],
   "source": {
    "title": "WHO fact sheet: Rabies; WHO Expert Consultation on Rabies, third report (2018)",
    "url": "https://www.who.int/news-room/fact-sheets/detail/rabies"
   },
   "en": "Dog bite (rabies exposure)",
   "fa": "گزیدن سگ (خطر هاری)",
   "ps": "د سپي چیچل (د هاري خطر)",
   "ask": "A bite or scratch from a dog or another animal."
  },
  {
   "id": "malaria",
   "active": false,
   "version": 1,
   "history": [],
   "definition": "Fever in a person living in or coming from a malaria area, with no other obvious cause. Not asked in the app yet: the book has no malaria page, and 'fever with no other cause' cannot be told apart by families.",
   "topics": [],
   "symptoms": [],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Suspected malaria",
   "fa": "ملاریا (مشکوک)",
   "ps": "ملاریا (شکمنه)",
   "ask": "Fever and shivering that keep coming back."
  },
  {
   "id": "tb",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Cough lasting 2 weeks or more (presumptive tuberculosis, needs testing). Not an outbreak disease; shown for trends only.",
   "topics": [
    "tb"
   ],
   "symptoms": [
    "longcough"
   ],
   "source": {
    "title": "WHO consolidated guidelines on tuberculosis, Module 2: screening (2021)",
    "url": "https://www.who.int/publications/i/item/9789240022676"
   },
   "en": "Cough 2 weeks or more (presumptive TB)",
   "fa": "سرفهٔ بیشتر از ۲ هفته (توبرکلوز؟)",
   "ps": "له ۲ اونیو زیات ټوخی (نری رنځ؟)",
   "ask": "A cough for 2 weeks or more."
  },
  {
   "id": "jaundice",
   "active": true,
   "version": 2,
   "history": [
    {
     "version": 1,
     "until": "2026-10-07",
     "topics": [
      "red-flags"
     ]
    }
   ],
   "definition": "Acute onset of yellow eyes or skin, with no known other cause, in anyone older than one month (acute jaundice syndrome; hepatitis A or E are common causes).",
   "topics": [
    "red-flags",
    "hepatitis"
   ],
   "symptoms": [
    "yellow"
   ],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions (acute jaundice syndrome)",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Acute jaundice (hepatitis?)",
   "fa": "زردی حاد (هپاتیت؟)",
   "ps": "حاد ژېړی (هیپاټایټس؟)",
   "ask": "Eyes or skin have recently turned yellow (not a newborn baby)."
  },
  {
   "id": "meningitis",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Sudden fever with a stiff neck, or with altered consciousness or other meningeal signs (bulging fontanelle in infants).",
   "topics": [
    "fever",
    "red-flags"
   ],
   "symptoms": [
    "fever"
   ],
   "source": {
    "title": "WHO Vaccine-Preventable Diseases Surveillance Standards: Meningitis (2018)",
    "url": "https://www.who.int/teams/immunization-vaccines-and-biologicals/immunization-analysis-and-insights/surveillance/surveillance-for-vpds/vpd-surveillance-standards"
   },
   "en": "Suspected meningitis",
   "fa": "مننژیت (مشکوک)",
   "ps": "مننژیت (شکمن)",
   "ask": "Fever with a stiff neck."
  },
  {
   "id": "leishmaniasis",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "A papule, nodule or ulcer of the skin that has not healed after 2 weeks in a person living in or coming from an area where leishmaniasis occurs.",
   "topics": [
    "leishmaniasis"
   ],
   "symptoms": [
    "sore"
   ],
   "source": {
    "title": "WHO fact sheet: Leishmaniasis; WHO Manual for case management of cutaneous leishmaniasis in the WHO Eastern Mediterranean Region (2014)",
    "url": "https://www.who.int/news-room/fact-sheets/detail/leishmaniasis"
   },
   "en": "Cutaneous leishmaniasis (salak)",
   "fa": "سالک (لیشمانیای جلدی)",
   "ps": "سالک (د پوستکي لیشمانیا)",
   "ask": "A skin sore that has not healed after two weeks."
  },
  {
   "id": "afp",
   "active": false,
   "version": 1,
   "history": [],
   "definition": "Any child under 15 with sudden onset of floppy (flaccid) weakness or paralysis of an arm or leg, or any person in whom a health worker suspects polio. Immediately notifiable. Not asked in the app yet: the book has no page on sudden weakness; add one before turning this on.",
   "topics": [],
   "symptoms": [],
   "source": {
    "title": "WHO Vaccine-Preventable Diseases Surveillance Standards: Poliomyelitis (2018)",
    "url": "https://www.who.int/teams/immunization-vaccines-and-biologicals/immunization-analysis-and-insights/surveillance/surveillance-for-vpds/vpd-surveillance-standards"
   },
   "en": "Acute flaccid paralysis (polio?)",
   "fa": "فلج شل حاد (پولیو؟)",
   "ps": "حاد شل فلج (پولیو؟)",
   "ask": "A child's arm or leg has suddenly gone floppy and will not move."
  }
 ],
 "alertRules": {
  "version": "2026-10-07.1",
  "unit": "one syndrome in one district in one ISO week (Monday to Sunday, by the report day on the phone), all age groups together; de-duplicated and voided reports are not counted",
  "baselineWeeks": 4,
  "rules": [
   {
    "id": "single",
    "kind": "any",
    "syndromes": [
     "cchf",
     "afp"
    ],
    "min": 1,
    "text": "Any single report of suspected CCHF or acute flaccid paralysis in a district in a week."
   },
   {
    "id": "measles-cluster",
    "kind": "any",
    "syndromes": [
     "measles"
    ],
    "min": 2,
    "text": "Two or more suspected measles reports in the same district in the same week."
   },
   {
    "id": "rise",
    "kind": "rise",
    "syndromes": "*",
    "min": 3,
    "ratio": 2,
    "text": "Three or more reports of one syndrome in a district in a week AND at least twice the baseline (the mean weekly count of the previous 4 weeks)."
   }
  ]
 },
 "suppression": {
  "minCell": 5,
  "text": "In shareable exports any count from 1 to 4 is shown as '<5'. Zero is shown as 0."
 },
 "placesVersion": "2026-10-07.1",
 "places": [
  {
   "id": "aybak-city",
   "en": "Aybak city",
   "fa": "شهر ایبک",
   "ps": "د ایبک ښار",
   "province": "Samangan"
  },
  {
   "id": "aybak",
   "en": "Aybak district (villages)",
   "fa": "اطراف ایبک (قریه‌ها)",
   "ps": "د ایبک شاوخوا کلي",
   "province": "Samangan"
  },
  {
   "id": "dara-i-suf-payin",
   "en": "Dara-i-Suf Payin",
   "fa": "دره صوف پایین",
   "ps": "دره صوف پایین",
   "province": "Samangan"
  },
  {
   "id": "dara-i-suf-bala",
   "en": "Dara-i-Suf Bala",
   "fa": "دره صوف بالا",
   "ps": "دره صوف بالا",
   "province": "Samangan"
  },
  {
   "id": "feroz-nakhchir",
   "en": "Feroz Nakhchir",
   "fa": "فیروز نخچیر",
   "ps": "فیروز نخچیر",
   "province": "Samangan"
  },
  {
   "id": "hazrat-i-sultan",
   "en": "Hazrat-i-Sultan",
   "fa": "حضرت سلطان",
   "ps": "حضرت سلطان",
   "province": "Samangan"
  },
  {
   "id": "khuram-wa-sarbagh",
   "en": "Khuram wa Sarbagh",
   "fa": "خرم و سارباغ",
   "ps": "خرم او سارباغ",
   "province": "Samangan"
  },
  {
   "id": "ruyi-du-ab",
   "en": "Ruyi Du Ab",
   "fa": "روی دوآب",
   "ps": "روی دوآب",
   "province": "Samangan"
  },
  {
   "id": "p-badakhshan",
   "en": "Badakhshan (province)",
   "fa": "ولایت بدخشان",
   "ps": "بدخشان ولایت",
   "province": "Badakhshan"
  },
  {
   "id": "p-badghis",
   "en": "Badghis (province)",
   "fa": "ولایت بادغیس",
   "ps": "بادغیس ولایت",
   "province": "Badghis"
  },
  {
   "id": "p-baghlan",
   "en": "Baghlan (province)",
   "fa": "ولایت بغلان",
   "ps": "بغلان ولایت",
   "province": "Baghlan"
  },
  {
   "id": "p-balkh",
   "en": "Balkh (province)",
   "fa": "ولایت بلخ",
   "ps": "بلخ ولایت",
   "province": "Balkh"
  },
  {
   "id": "p-bamyan",
   "en": "Bamyan (province)",
   "fa": "ولایت بامیان",
   "ps": "بامیان ولایت",
   "province": "Bamyan"
  },
  {
   "id": "p-daykundi",
   "en": "Daykundi (province)",
   "fa": "ولایت دایکندی",
   "ps": "دایکندي ولایت",
   "province": "Daykundi"
  },
  {
   "id": "p-farah",
   "en": "Farah (province)",
   "fa": "ولایت فراه",
   "ps": "فراه ولایت",
   "province": "Farah"
  },
  {
   "id": "p-faryab",
   "en": "Faryab (province)",
   "fa": "ولایت فاریاب",
   "ps": "فاریاب ولایت",
   "province": "Faryab"
  },
  {
   "id": "p-ghazni",
   "en": "Ghazni (province)",
   "fa": "ولایت غزنی",
   "ps": "غزني ولایت",
   "province": "Ghazni"
  },
  {
   "id": "p-ghor",
   "en": "Ghor (province)",
   "fa": "ولایت غور",
   "ps": "غور ولایت",
   "province": "Ghor"
  },
  {
   "id": "p-helmand",
   "en": "Helmand (province)",
   "fa": "ولایت هلمند",
   "ps": "هلمند ولایت",
   "province": "Helmand"
  },
  {
   "id": "p-herat",
   "en": "Herat (province)",
   "fa": "ولایت هرات",
   "ps": "هرات ولایت",
   "province": "Herat"
  },
  {
   "id": "p-jowzjan",
   "en": "Jowzjan (province)",
   "fa": "ولایت جوزجان",
   "ps": "جوزجان ولایت",
   "province": "Jowzjan"
  },
  {
   "id": "p-kabul",
   "en": "Kabul (province)",
   "fa": "ولایت کابل",
   "ps": "کابل ولایت",
   "province": "Kabul"
  },
  {
   "id": "p-kandahar",
   "en": "Kandahar (province)",
   "fa": "ولایت کندهار",
   "ps": "کندهار ولایت",
   "province": "Kandahar"
  },
  {
   "id": "p-kapisa",
   "en": "Kapisa (province)",
   "fa": "ولایت کاپیسا",
   "ps": "کاپیسا ولایت",
   "province": "Kapisa"
  },
  {
   "id": "p-khost",
   "en": "Khost (province)",
   "fa": "ولایت خوست",
   "ps": "خوست ولایت",
   "province": "Khost"
  },
  {
   "id": "p-kunar",
   "en": "Kunar (province)",
   "fa": "ولایت کنر",
   "ps": "کونړ ولایت",
   "province": "Kunar"
  },
  {
   "id": "p-kunduz",
   "en": "Kunduz (province)",
   "fa": "ولایت کندز",
   "ps": "کندز ولایت",
   "province": "Kunduz"
  },
  {
   "id": "p-laghman",
   "en": "Laghman (province)",
   "fa": "ولایت لغمان",
   "ps": "لغمان ولایت",
   "province": "Laghman"
  },
  {
   "id": "p-logar",
   "en": "Logar (province)",
   "fa": "ولایت لوگر",
   "ps": "لوګر ولایت",
   "province": "Logar"
  },
  {
   "id": "p-nangarhar",
   "en": "Nangarhar (province)",
   "fa": "ولایت ننگرهار",
   "ps": "ننګرهار ولایت",
   "province": "Nangarhar"
  },
  {
   "id": "p-nimroz",
   "en": "Nimroz (province)",
   "fa": "ولایت نیمروز",
   "ps": "نیمروز ولایت",
   "province": "Nimroz"
  },
  {
   "id": "p-nuristan",
   "en": "Nuristan (province)",
   "fa": "ولایت نورستان",
   "ps": "نورستان ولایت",
   "province": "Nuristan"
  },
  {
   "id": "p-paktia",
   "en": "Paktia (province)",
   "fa": "ولایت پکتیا",
   "ps": "پکتیا ولایت",
   "province": "Paktia"
  },
  {
   "id": "p-paktika",
   "en": "Paktika (province)",
   "fa": "ولایت پکتیکا",
   "ps": "پکتیکا ولایت",
   "province": "Paktika"
  },
  {
   "id": "p-panjshir",
   "en": "Panjshir (province)",
   "fa": "ولایت پنجشیر",
   "ps": "پنجشیر ولایت",
   "province": "Panjshir"
  },
  {
   "id": "p-parwan",
   "en": "Parwan (province)",
   "fa": "ولایت پروان",
   "ps": "پروان ولایت",
   "province": "Parwan"
  },
  {
   "id": "p-sar-e-pol",
   "en": "Sar-e Pol (province)",
   "fa": "ولایت سرپل",
   "ps": "سرپل ولایت",
   "province": "Sar-e Pol"
  },
  {
   "id": "p-takhar",
   "en": "Takhar (province)",
   "fa": "ولایت تخار",
   "ps": "تخار ولایت",
   "province": "Takhar"
  },
  {
   "id": "p-uruzgan",
   "en": "Uruzgan (province)",
   "fa": "ولایت ارزگان",
   "ps": "ارزګان ولایت",
   "province": "Uruzgan"
  },
  {
   "id": "p-wardak",
   "en": "Wardak (province)",
   "fa": "ولایت میدان وردک",
   "ps": "میدان وردګ ولایت",
   "province": "Wardak"
  },
  {
   "id": "p-zabul",
   "en": "Zabul (province)",
   "fa": "ولایت زابل",
   "ps": "زابل ولایت",
   "province": "Zabul"
  }
 ]
};
