// GENERATED by tools/build.py from content/src/syndromes.json and content/src/districts.json. Do not edit by hand.
export default {
 "version": "2026-10-07.1",
 "dedupeDays": 14,
 "ageGroups": [
  {
   "id": "u5",
   "en": "Child under 5"
  },
  {
   "id": "5-14",
   "en": "Older child (5 to 14)"
  },
  {
   "id": "15+",
   "en": "Adult (15 and over)"
  }
 ],
 "syndromes": [
  {
   "id": "measles",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Any person with fever and a maculopapular (non-vesicular) rash, or in whom a health worker suspects measles. App wording: fever and a red rash all over the body.",
   "topics": [
    "measles",
    "fever"
   ],
   "symptoms": [
    "rash"
   ],
   "source": {
    "title": "WHO Vaccine-Preventable Diseases Surveillance Standards: Measles (2018)",
    "url": "https://www.who.int/teams/immunization-vaccines-and-biologicals/immunization-analysis-and-insights/surveillance/surveillance-for-vpds/vpd-surveillance-standards"
   },
   "en": "Suspected measles",
   "ask": "Fever and a red rash all over the body; it may be measles."
  },
  {
   "id": "awd",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Three or more loose or watery stools in 24 hours, without visible blood.",
   "topics": [
    "diarrhoea"
   ],
   "symptoms": [
    "diarrhoea"
   ],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Acute watery diarrhoea",
   "ask": "Three or more watery stools in one day, with no blood."
  },
  {
   "id": "bloody-diarrhoea",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Acute diarrhoea with visible blood in the stool.",
   "topics": [
    "diarrhoea"
   ],
   "symptoms": [
    "diarrhoea"
   ],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Bloody diarrhoea",
   "ask": "Diarrhoea, with blood in the stool."
  },
  {
   "id": "ari",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Cough or difficult breathing with fast breathing (IMCI cut-offs by age) or lower chest indrawing (ARI-pneumonia). Lay report, breathing not counted by a health worker.",
   "topics": [
    "cough"
   ],
   "symptoms": [
    "breathing",
    "cough"
   ],
   "source": {
    "title": "WHO IMCI Chart Booklet (2014) and WHO EMRO Afghanistan outbreak situation reports (ARI-pneumonia)",
    "url": "https://www.emro.who.int/images/stories/afghanistan/Afghanistan-Outbreaks-Situation-report-week-43-2025.pdf"
   },
   "en": "Acute respiratory infection / pneumonia",
   "ask": "Cough with fast or difficult breathing."
  },
  {
   "id": "cchf",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Sudden onset of fever with bleeding (nose, gums, skin, vomit or stool), especially after a tick bite or contact with animal blood or a sick person. Immediately notifiable.",
   "topics": [
    "animal-illness"
   ],
   "symptoms": [
    "animals"
   ],
   "source": {
    "title": "WHO fact sheet: Crimean-Congo haemorrhagic fever; WHO EMRO Afghanistan outbreak situation reports (suspected CCHF)",
    "url": "https://www.who.int/news-room/fact-sheets/detail/crimean-congo-haemorrhagic-fever"
   },
   "en": "Suspected CCHF (Congo fever)",
   "ask": "Sudden fever with bleeding from the nose, gums or under the skin."
  },
  {
   "id": "dog-bite",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Any person bitten or scratched by a dog or another animal that may carry rabies (possible rabies exposure).",
   "topics": [
    "first-aid",
    "animal-illness"
   ],
   "symptoms": [
    "bite"
   ],
   "source": {
    "title": "WHO fact sheet: Rabies; WHO Expert Consultation on Rabies, third report (2018)",
    "url": "https://www.who.int/news-room/fact-sheets/detail/rabies"
   },
   "en": "Dog bite (rabies exposure)",
   "ask": "A bite or scratch from a dog or another animal."
  },
  {
   "id": "malaria",
   "active": false,
   "version": 1,
   "history": [],
   "definition": "Fever in a person living in or coming from a malaria area, with no other obvious cause. Not asked in the app yet: the book has no malaria page, and 'fever with no other cause' cannot be told apart by families.",
   "topics": [],
   "symptoms": [],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Suspected malaria",
   "ask": "Fever and shivering that keep coming back."
  },
  {
   "id": "tb",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Cough lasting 2 weeks or more (presumptive tuberculosis, needs testing). Not an outbreak disease; shown for trends only.",
   "topics": [
    "tb"
   ],
   "symptoms": [
    "longcough"
   ],
   "source": {
    "title": "WHO consolidated guidelines on tuberculosis, Module 2: screening (2021)",
    "url": "https://www.who.int/publications/i/item/9789240022676"
   },
   "en": "Cough 2 weeks or more (presumptive TB)",
   "ask": "A cough for 2 weeks or more."
  },
  {
   "id": "jaundice",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Acute onset of yellow eyes or skin, with no known other cause, in anyone older than one month (acute jaundice syndrome; hepatitis A or E are common causes).",
   "topics": [
    "red-flags"
   ],
   "symptoms": [
    "yellow"
   ],
   "source": {
    "title": "WHO (2012) Outbreak surveillance and response in humanitarian emergencies: guidelines for EWARN implementation, standard case definitions (acute jaundice syndrome)",
    "url": "https://www.who.int/publications/i/item/outbreak-surveillance-and-response-in-humanitarian-emergencies-who-guidelines-for-ewarn-implementation"
   },
   "en": "Acute jaundice (hepatitis?)",
   "ask": "Eyes or skin have recently turned yellow (not a newborn baby)."
  },
  {
   "id": "meningitis",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "Sudden fever with a stiff neck, or with altered consciousness or other meningeal signs (bulging fontanelle in infants).",
   "topics": [
    "fever",
    "red-flags"
   ],
   "symptoms": [
    "fever"
   ],
   "source": {
    "title": "WHO Vaccine-Preventable Diseases Surveillance Standards: Meningitis (2018)",
    "url": "https://www.who.int/teams/immunization-vaccines-and-biologicals/immunization-analysis-and-insights/surveillance/surveillance-for-vpds/vpd-surveillance-standards"
   },
   "en": "Suspected meningitis",
   "ask": "Fever with a stiff neck."
  },
  {
   "id": "leishmaniasis",
   "active": true,
   "version": 1,
   "history": [],
   "definition": "A papule, nodule or ulcer of the skin that has not healed after 2 weeks in a person living in or coming from an area where leishmaniasis occurs.",
   "topics": [
    "leishmaniasis"
   ],
   "symptoms": [
    "sore"
   ],
   "source": {
    "title": "WHO fact sheet: Leishmaniasis; WHO Manual for case management of cutaneous leishmaniasis in the WHO Eastern Mediterranean Region (2014)",
    "url": "https://www.who.int/news-room/fact-sheets/detail/leishmaniasis"
   },
   "en": "Cutaneous leishmaniasis (salak)",
   "ask": "A skin sore that has not healed after two weeks."
  },
  {
   "id": "afp",
   "active": false,
   "version": 1,
   "history": [],
   "definition": "Any child under 15 with sudden onset of floppy (flaccid) weakness or paralysis of an arm or leg, or any person in whom a health worker suspects polio. Immediately notifiable. Not asked in the app yet: the book has no page on sudden weakness; add one before turning this on.",
   "topics": [],
   "symptoms": [],
   "source": {
    "title": "WHO Vaccine-Preventable Diseases Surveillance Standards: Poliomyelitis (2018)",
    "url": "https://www.who.int/teams/immunization-vaccines-and-biologicals/immunization-analysis-and-insights/surveillance/surveillance-for-vpds/vpd-surveillance-standards"
   },
   "en": "Acute flaccid paralysis (polio?)",
   "ask": "A child's arm or leg has suddenly gone floppy and will not move."
  }
 ],
 "alertRules": {
  "version": "2026-10-07.1",
  "unit": "one syndrome in one district in one ISO week (Monday to Sunday, by the report day on the phone), all age groups together; de-duplicated and voided reports are not counted",
  "baselineWeeks": 4,
  "rules": [
   {
    "id": "single",
    "kind": "any",
    "syndromes": [
     "cchf",
     "afp"
    ],
    "min": 1,
    "text": "Any single report of suspected CCHF or acute flaccid paralysis in a district in a week."
   },
   {
    "id": "measles-cluster",
    "kind": "any",
    "syndromes": [
     "measles"
    ],
    "min": 2,
    "text": "Two or more suspected measles reports in the same district in the same week."
   },
   {
    "id": "rise",
    "kind": "rise",
    "syndromes": "*",
    "min": 3,
    "ratio": 2,
    "text": "Three or more reports of one syndrome in a district in a week AND at least twice the baseline (the mean weekly count of the previous 4 weeks)."
   }
  ]
 },
 "suppression": {
  "minCell": 5,
  "text": "In shareable exports any count from 1 to 4 is shown as '<5'. Zero is shown as 0."
 },
 "placesVersion": "2026-10-07.1",
 "places": [
  {
   "id": "aybak-city",
   "en": "Aybak city",
   "province": "Samangan"
  },
  {
   "id": "aybak",
   "en": "Aybak district (villages)",
   "province": "Samangan"
  },
  {
   "id": "dara-i-suf-payin",
   "en": "Dara-i-Suf Payin",
   "province": "Samangan"
  },
  {
   "id": "dara-i-suf-bala",
   "en": "Dara-i-Suf Bala",
   "province": "Samangan"
  },
  {
   "id": "feroz-nakhchir",
   "en": "Feroz Nakhchir",
   "province": "Samangan"
  },
  {
   "id": "hazrat-i-sultan",
   "en": "Hazrat-i-Sultan",
   "province": "Samangan"
  },
  {
   "id": "khuram-wa-sarbagh",
   "en": "Khuram wa Sarbagh",
   "province": "Samangan"
  },
  {
   "id": "ruyi-du-ab",
   "en": "Ruyi Du Ab",
   "province": "Samangan"
  },
  {
   "id": "p-badakhshan",
   "en": "Badakhshan (province)",
   "province": "Badakhshan"
  },
  {
   "id": "p-badghis",
   "en": "Badghis (province)",
   "province": "Badghis"
  },
  {
   "id": "p-baghlan",
   "en": "Baghlan (province)",
   "province": "Baghlan"
  },
  {
   "id": "p-balkh",
   "en": "Balkh (province)",
   "province": "Balkh"
  },
  {
   "id": "p-bamyan",
   "en": "Bamyan (province)",
   "province": "Bamyan"
  },
  {
   "id": "p-daykundi",
   "en": "Daykundi (province)",
   "province": "Daykundi"
  },
  {
   "id": "p-farah",
   "en": "Farah (province)",
   "province": "Farah"
  },
  {
   "id": "p-faryab",
   "en": "Faryab (province)",
   "province": "Faryab"
  },
  {
   "id": "p-ghazni",
   "en": "Ghazni (province)",
   "province": "Ghazni"
  },
  {
   "id": "p-ghor",
   "en": "Ghor (province)",
   "province": "Ghor"
  },
  {
   "id": "p-helmand",
   "en": "Helmand (province)",
   "province": "Helmand"
  },
  {
   "id": "p-herat",
   "en": "Herat (province)",
   "province": "Herat"
  },
  {
   "id": "p-jowzjan",
   "en": "Jowzjan (province)",
   "province": "Jowzjan"
  },
  {
   "id": "p-kabul",
   "en": "Kabul (province)",
   "province": "Kabul"
  },
  {
   "id": "p-kandahar",
   "en": "Kandahar (province)",
   "province": "Kandahar"
  },
  {
   "id": "p-kapisa",
   "en": "Kapisa (province)",
   "province": "Kapisa"
  },
  {
   "id": "p-khost",
   "en": "Khost (province)",
   "province": "Khost"
  },
  {
   "id": "p-kunar",
   "en": "Kunar (province)",
   "province": "Kunar"
  },
  {
   "id": "p-kunduz",
   "en": "Kunduz (province)",
   "province": "Kunduz"
  },
  {
   "id": "p-laghman",
   "en": "Laghman (province)",
   "province": "Laghman"
  },
  {
   "id": "p-logar",
   "en": "Logar (province)",
   "province": "Logar"
  },
  {
   "id": "p-nangarhar",
   "en": "Nangarhar (province)",
   "province": "Nangarhar"
  },
  {
   "id": "p-nimroz",
   "en": "Nimroz (province)",
   "province": "Nimroz"
  },
  {
   "id": "p-nuristan",
   "en": "Nuristan (province)",
   "province": "Nuristan"
  },
  {
   "id": "p-paktia",
   "en": "Paktia (province)",
   "province": "Paktia"
  },
  {
   "id": "p-paktika",
   "en": "Paktika (province)",
   "province": "Paktika"
  },
  {
   "id": "p-panjshir",
   "en": "Panjshir (province)",
   "province": "Panjshir"
  },
  {
   "id": "p-parwan",
   "en": "Parwan (province)",
   "province": "Parwan"
  },
  {
   "id": "p-sar-e-pol",
   "en": "Sar-e Pol (province)",
   "province": "Sar-e Pol"
  },
  {
   "id": "p-takhar",
   "en": "Takhar (province)",
   "province": "Takhar"
  },
  {
   "id": "p-uruzgan",
   "en": "Uruzgan (province)",
   "province": "Uruzgan"
  },
  {
   "id": "p-wardak",
   "en": "Wardak (province)",
   "province": "Wardak"
  },
  {
   "id": "p-zabul",
   "en": "Zabul (province)",
   "province": "Zabul"
  }
 ]
};
