"""Wrap server/about.html (the dashboard's "About this app" page) into server/about.js so the server can serve it.
Run after server/about.html changes: python3 tools/make_about.py"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
html = open(os.path.join(ROOT, "server", "about.html"), encoding="utf-8").read()
open(os.path.join(ROOT, "server", "about.js"), "w", encoding="utf-8").write(
    "// Generated by tools/make_about.py from server/about.html. Do not edit by hand.\nexport default " + json.dumps(html, ensure_ascii=False) + ";\n")
print("wrote server/about.js")
